### ISSUE TITLE
Quickstart Instructions

### ISSUE THREAD

**Issue by kailinprime** [larrychristensen/orcpub#3]
Can you patch the README with quick start instructions?

**Comment by kjstouffer** [comment]
This is what i've discovered so far (also, some instructions are present https://github.com/larrychristensen/messenjer)

Install Java: http://openjdk.java.net/ or http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
Install leiningen: https://leiningen.org/
run `lein figwheel`
that should get a basic dev environment going.

Additionally, I had to explicitly allow insecure connections to repositories in the `project.clj` by appending this to the end of it:
```clojure
;; never do this
(require 'cemerick.pomegranate.aether)
(cemerick.pomegranate.aether/register-wagon-factory!
 "http" #(org.apache.maven.wagon.providers.http.HttpWagon.))
```

after that, I had to remove the
```clojure
["my.datomic.com" {:url "https://my.datomic.com/repo"
                    :username [:gpg :env]
                    :password [:gpg :env]}]]
```
and replace `[com.datomic/datomic-pro "0.9.5561"]` with `[com.datomic/datomic-free "0.9.5697"]`

then `lein figwheel` actually succeeded and started a local webserver. it appears that the local webserver is missing quite a few resources

if you want to run lein `figwheel-native` i also had to delete the `yarn.lock` file

My setup still isn't correct though because the background is white instead of the black-blue gradient. But things seem to be working.

**Comment by larrychristensen** [comment]
I've added more info on starting things up here: https://github.com/larrychristensen/messenjer/blob/master/README.md

**Comment by codeGlaze** [comment]
@kjstoufer Did you need to make an account for the free datomic?
That was the last thing I had to change the other night but I ran out of time.

Otherwise my fixes were exactly the same.

**Comment by larrychristensen** [comment]
I'll add instructions on getting it fully working with Datomic tomorrow.
Thanks!

**Comment by kjstouffer** [comment]
@codeGlaze I haven't actually tried setting up datomic yet, but the datomic-free jar is in one of the other repositories.  I didn't need to make an account to download datomic free either (https://my.datomic.com/downloads/free), but i don't know if i need an account to _use_ it. I did some reading yesterday and it looks like datomic free has limitations that are probably okay for dev, but not likely for production (and requires making an account). I'm not familiar with datomic at all, so i don't know if the free version would require a code change given the `"?aws_access_key_id="` params in `system.clj`
